const mdn = 'https://developer.mozilla.org/en-US/docs/';
const react = 'https://react.dev/learn/';

export const groups = [
  { name: 'Start here', label: 'The big picture' },
  { name: 'JavaScript basics', label: 'Learn the language' },
  { name: 'Web pages', label: 'Make a page respond' },
  { name: 'React basics', label: 'Build with components' },
];

export const articles = [
  {
    id: 'welcome',
    group: 'Start here',
    title: 'Welcome',
    desc: 'A calm place to learn JavaScript, one small idea at a time.',
    intro: [
      'You do not need to memorize everything on this site.',
      'Read one lesson. Change the example. Then move on when the idea feels familiar.',
    ],
    analogy: {
      title: 'Learning to cook',
      text: 'You would not memorize an entire cookbook before making breakfast. Coding works the same way: learn one recipe, try it, and build from there.',
    },
    syntax: '// JavaScript can store information\nconst name = "Maya";\n\n// It can also do something with that information\nconsole.log("Hello, " + name);',
    breakdown: [
      ['const name = "Maya"', 'Save the text “Maya” and give it the label name.'],
      ['console.log(...)', 'Show a message in the browser console.'],
      ['"Hello, " + name', 'Join two pieces of text together.'],
    ],
    tryIt: 'Change “Maya” to your name. What message do you expect to see?',
    remember: 'Coding is mostly breaking a large problem into small, clear steps.',
    source: mdn + 'Learn_web_development/Getting_started/Your_first_website',
  },
  {
    id: 'web-basics',
    group: 'Start here',
    title: 'How a website works',
    desc: 'HTML, CSS, and JavaScript each have one main job.',
    intro: [
      'HTML holds the content. CSS controls how it looks. JavaScript controls what happens.',
      'React comes later. It is a tool built with JavaScript that helps you organize interactive pages.',
    ],
    analogy: {
      title: 'Think of a house',
      text: 'HTML is the frame and rooms. CSS is the paint and furniture. JavaScript is the electricity: it makes switches, doors, and appliances work.',
    },
    syntax: '<!-- HTML: the content -->\n<button id="hello">Say hello</button>\n\n/* CSS: the look */\nbutton { background: gold; }\n\n// JavaScript: the action\ndocument.querySelector("#hello").onclick = () => {\n  alert("Hello!");\n};',
    breakdown: [
      ['HTML', 'Creates a button the visitor can see.'],
      ['CSS', 'Changes the button’s color.'],
      ['JavaScript', 'Shows a message when the visitor clicks.'],
    ],
    tryIt: 'Imagine a light switch on a page. Which part creates it, which styles it, and which makes it work?',
    remember: 'Start with JavaScript before React. React makes more sense when the language underneath feels familiar.',
    source: mdn + 'Learn_web_development/Getting_started/Web_standards/The_web_standards_model',
  },
  {
    id: 'first-steps',
    group: 'Start here',
    title: 'Run your first code',
    desc: 'Use the browser console as a quick practice space.',
    intro: [
      'Open a web page. Then open your browser’s developer tools and choose the Console tab.',
      'The console lets you try one line of JavaScript and see the result right away.',
    ],
    analogy: {
      title: 'A coding scratchpad',
      text: 'The console is like scrap paper beside a notebook. It is perfect for quick experiments. Your project files are where you keep the code you want to save.',
    },
    syntax: '2 + 2;\n// 4\n\nconst snack = "mango";\nconsole.log(snack);\n// mango',
    breakdown: [
      ['2 + 2', 'JavaScript calculates the answer.'],
      ['const snack = "mango"', 'JavaScript remembers a piece of text.'],
      ['// mango', 'A line starting with // is a note for people. JavaScript ignores it.'],
    ],
    tryIt: 'Change the snack to your favorite food. Then type console.log(snack).',
    remember: 'Errors are normal. Read the first line of the error, check the spelling, and try again.',
    source: mdn + 'Learn_web_development/Howto/Tools_and_setup/What_are_browser_developer_tools',
  },
  {
    id: 'variables',
    group: 'JavaScript basics',
    title: 'Variables',
    desc: 'Give a value a useful name so you can use it later.',
    intro: [
      'A variable is a name that points to a value.',
      'Use const by default. Use let only when you plan to replace the value later.',
    ],
    analogy: {
      title: 'Labels on containers',
      text: 'A variable is like a label on a kitchen container. A label such as sugar is easier to understand than “the white powder in the second jar.”',
    },
    syntax: 'const playerName = "Maya";\nlet score = 0;\n\nscore = score + 10;\n\nconsole.log(playerName); // Maya\nconsole.log(score);      // 10',
    breakdown: [
      ['const playerName', 'Create a name that will not point to a different value later.'],
      ['let score', 'Create a name whose value can be replaced.'],
      ['score = score + 10', 'Read the old score, add 10, and save the result.'],
    ],
    tryIt: 'Start score at 5. Add 10 twice. What should the final score be?',
    remember: 'Use clear names. totalPrice tells you more than x.',
    source: mdn + 'Learn_web_development/Core/Scripting/Variables',
  },
  {
    id: 'types',
    group: 'JavaScript basics',
    title: 'Types of values',
    desc: 'Text, numbers, and true-or-false values behave differently.',
    intro: [
      'A value has a type. Its type tells JavaScript what kind of information it holds.',
      'For now, focus on strings, numbers, and booleans.',
    ],
    analogy: {
      title: 'Different drawers',
      text: 'A desk has separate drawers for pens, paper, and cables. JavaScript types also separate values by what they are and what you can do with them.',
    },
    syntax: 'const username = "Maya"; // string: text\nconst age = 24;          // number\nconst isOnline = true;   // boolean\n\nconsole.log(typeof age); // "number"',
    breakdown: [
      ['String', 'Text inside quotes, such as "Maya" or "24".'],
      ['Number', 'A number without quotes, such as 24 or 3.5.'],
      ['Boolean', 'Only true or false. Useful for yes-or-no questions.'],
    ],
    tryIt: 'Try typeof "24" and typeof 24 in the console. The quotes change the type.',
    remember: '"5" is text. 5 is a number. They may look alike, but JavaScript treats them differently.',
    source: mdn + 'Web/JavaScript/Guide/Data_structures',
  },
  {
    id: 'conditions',
    group: 'JavaScript basics',
    title: 'Make decisions',
    desc: 'Use if and else to choose which code should run.',
    intro: [
      'A condition asks a yes-or-no question.',
      'If the answer is true, JavaScript runs one block of code. Otherwise, it can run another.',
    ],
    analogy: {
      title: 'A door with a rule',
      text: 'A cinema might ask, “Do you have a ticket?” If yes, you enter. If no, you go to the ticket counter. An if statement follows the same pattern.',
    },
    syntax: 'const hasTicket = true;\n\nif (hasTicket) {\n  console.log("Come in!");\n} else {\n  console.log("Please buy a ticket.");\n}',
    breakdown: [
      ['if (hasTicket)', 'Check whether hasTicket is true.'],
      ['{ ... }', 'Run the code inside these braces when the check passes.'],
      ['else', 'Run a different block when the check does not pass.'],
    ],
    tryIt: 'Change hasTicket to false. Which message should appear now?',
    remember: 'Use === when comparing values: age === 18 checks both the value and its type.',
    source: mdn + 'Learn_web_development/Core/Scripting/Conditionals',
  },
  {
    id: 'functions',
    group: 'JavaScript basics',
    title: 'Functions',
    desc: 'Group steps into a reusable action.',
    intro: [
      'A function is a small set of instructions with a name.',
      'It can receive information, do some work, and return an answer.',
    ],
    analogy: {
      title: 'A coffee machine',
      text: 'You give a coffee machine water and beans. It follows the same steps each time and gives you coffee. A function turns inputs into an output in the same way.',
    },
    syntax: 'function greet(name) {\n  return "Hello, " + name + "!";\n}\n\nconst message = greet("Maya");\nconsole.log(message); // Hello, Maya!',
    breakdown: [
      ['function greet(name)', 'Create a function named greet. name is its input.'],
      ['return', 'Send the finished value back to the caller.'],
      ['greet("Maya")', 'Run the function with “Maya” as the input.'],
    ],
    tryIt: 'Call greet with your own name. Then change the greeting to say “Welcome”.',
    remember: 'Creating a function does not run it. Add parentheses—greet()—when you want it to run.',
    source: mdn + 'Learn_web_development/Core/Scripting/Functions',
  },
  {
    id: 'arrays',
    group: 'JavaScript basics',
    title: 'Arrays',
    desc: 'Keep a list of related values in one place.',
    intro: [
      'An array is an ordered list. Each item has a position called an index.',
      'The first item is at index 0, not index 1.',
    ],
    analogy: {
      title: 'A numbered shopping list',
      text: 'An array is like a shopping list where every line has a number. JavaScript starts numbering those lines at zero.',
    },
    syntax: 'const fruits = ["mango", "banana", "apple"];\n\nconsole.log(fruits[0]);     // mango\nconsole.log(fruits.length); // 3\n\nfruits.push("orange");\nconsole.log(fruits.length); // 4',
    breakdown: [
      ['fruits[0]', 'Get the first item. Square brackets choose a position.'],
      ['fruits.length', 'Count how many items are in the array.'],
      ['fruits.push(...)', 'Add a new item to the end.'],
    ],
    tryIt: 'Make an array with three favorite songs. Print the second song with songs[1].',
    remember: 'Arrays start at 0. The last item is at array.length - 1.',
    source: mdn + 'Learn_web_development/Core/Scripting/Arrays',
  },
  {
    id: 'objects',
    group: 'JavaScript basics',
    title: 'Objects',
    desc: 'Keep related facts about one thing together.',
    intro: [
      'An object stores values under names called properties.',
      'Use an object when several pieces of information belong to the same thing.',
    ],
    analogy: {
      title: 'A contact card',
      text: 'A contact card groups a person’s name, phone number, and email. An object groups related information in much the same way.',
    },
    syntax: 'const player = {\n  name: "Maya",\n  score: 10,\n  isOnline: true\n};\n\nconsole.log(player.name); // Maya\nplayer.score = 20;',
    breakdown: [
      ['name: "Maya"', 'A property name and its value.'],
      ['player.name', 'Read the name property from player.'],
      ['player.score = 20', 'Replace one property value.'],
    ],
    tryIt: 'Create a book object with title, author, and pageCount properties.',
    remember: 'Use an array for a list. Use an object for facts about one item.',
    source: mdn + 'Learn_web_development/Core/Scripting/Object_basics',
  },
  {
    id: 'dom',
    group: 'Web pages',
    title: 'Change the page',
    desc: 'JavaScript can find an HTML element and update it.',
    intro: [
      'The browser turns your HTML into a page model called the DOM.',
      'JavaScript can find pieces of that model and change what the visitor sees.',
    ],
    analogy: {
      title: 'A map of the page',
      text: 'Think of the DOM as a map where every heading, button, and paragraph has a location. querySelector helps JavaScript find one location on that map.',
    },
    syntax: '<h1 id="title">Old title</h1>\n\n<script>\n  const title = document.querySelector("#title");\n  title.textContent = "New title";\n</script>',
    breakdown: [
      ['id="title"', 'Give the heading a unique label in HTML.'],
      ['document.querySelector("#title")', 'Find the element with that label.'],
      ['title.textContent = ...', 'Replace the text inside the element.'],
    ],
    tryIt: 'Change “New title” to a greeting. What will the heading show?',
    remember: 'JavaScript can only find an element after the browser has created it.',
    source: mdn + 'Learn_web_development/Core/Scripting/DOM_scripting',
  },
  {
    id: 'events',
    group: 'Web pages',
    title: 'Respond to clicks',
    desc: 'An event tells your code that something happened.',
    intro: [
      'Clicks, typing, and form submissions are events.',
      'You choose an element, name the event, and give JavaScript a function to run.',
    ],
    analogy: {
      title: 'A doorbell',
      text: 'A doorbell waits quietly. When someone presses it, it signals you to act. An event listener also waits, then runs your function at the right moment.',
    },
    syntax: 'const button = document.querySelector("button");\n\nbutton.addEventListener("click", () => {\n  console.log("The button was clicked!");\n});',
    breakdown: [
      ['addEventListener', 'Tell the browser to listen for something.'],
      ['"click"', 'The event we care about.'],
      ['() => { ... }', 'The function to run after the click.'],
    ],
    tryIt: 'Add a button to a page. Make a console message appear when you click it.',
    remember: 'Pass the function to the listener. Do not call it early with parentheses.',
    source: mdn + 'Learn_web_development/Core/Scripting/Events',
  },
  {
    id: 'async',
    group: 'Web pages',
    title: 'Wait for data',
    desc: 'Use async and await when an answer takes time.',
    intro: [
      'Some work does not finish right away. Loading data from the internet is one example.',
      'await pauses the current function until the result is ready. The rest of the page can keep working.',
    ],
    analogy: {
      title: 'A restaurant order',
      text: 'You place an order, then wait for your food. The restaurant does not close while your meal is cooking. Other people can still order and eat.',
    },
    syntax: 'async function loadMessage() {\n  try {\n    const response = await fetch("/message.json");\n    const data = await response.json();\n    console.log(data.message);\n  } catch (error) {\n    console.log("Could not load the message.");\n  }\n}',
    breakdown: [
      ['async function', 'Mark a function that needs to wait for work.'],
      ['await fetch(...)', 'Wait for the server to respond.'],
      ['try / catch', 'Try the work, then handle a problem if it fails.'],
    ],
    tryIt: 'Read the example from top to bottom. Which line waits for the server?',
    remember: 'Network requests can fail. Show a helpful loading state and error message.',
    source: mdn + 'Learn_web_development/Extensions/Async_JS/Promises',
  },
  {
    id: 'components',
    group: 'React basics',
    title: 'Components',
    desc: 'Build a page from small, reusable pieces.',
    intro: [
      'A React component is a JavaScript function that returns part of the page.',
      'Component names start with a capital letter. You can use them like HTML tags.',
    ],
    analogy: {
      title: 'Reusable building blocks',
      text: 'A toy set uses the same wheel piece on many cars. A website can reuse the same Button or ProfileCard component in many places.',
    },
    syntax: 'function Welcome() {\n  return <h1>Hello!</h1>;\n}\n\nexport default function App() {\n  return (\n    <main>\n      <Welcome />\n      <Welcome />\n    </main>\n  );\n}',
    breakdown: [
      ['function Welcome()', 'Create a component named Welcome.'],
      ['return <h1>...</h1>', 'Describe what should appear on the page.'],
      ['<Welcome />', 'Use the component. Here it appears twice.'],
    ],
    tryIt: 'Create a component named Footer that returns a short paragraph.',
    remember: 'Keep components small enough that their job is easy to explain.',
    source: react + 'your-first-component',
  },
  {
    id: 'props',
    group: 'React basics',
    title: 'Props',
    desc: 'Give a component information to display.',
    intro: [
      'Props are inputs for a component.',
      'They let one component show different information without copying the whole component.',
    ],
    analogy: {
      title: 'A name badge printer',
      text: 'The printer follows one design, but you give it a different name each time. The design is the component. The name is a prop.',
    },
    syntax: 'function Welcome({ name }) {\n  return <h2>Hello, {name}!</h2>;\n}\n\nexport default function App() {\n  return (\n    <>\n      <Welcome name="Maya" />\n      <Welcome name="Sam" />\n    </>\n  );\n}',
    breakdown: [
      ['{ name }', 'Receive the name prop inside the component.'],
      ['{name}', 'Place a JavaScript value inside JSX.'],
      ['name="Maya"', 'Send the value “Maya” to the component.'],
    ],
    tryIt: 'Add a second prop named city and show it under the greeting.',
    remember: 'Props are read-only. A component should not change the props it receives.',
    source: react + 'passing-props-to-a-component',
  },
  {
    id: 'state',
    group: 'React basics',
    title: 'State',
    desc: 'Let a component remember something that can change.',
    intro: [
      'State is a component’s memory.',
      'When state changes, React runs the component again and updates the screen.',
    ],
    analogy: {
      title: 'A scoreboard',
      text: 'A scoreboard remembers the current score. When the score changes, the display updates. State does the same job for a component.',
    },
    syntax: 'import { useState } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Clicks: {count}\n    </button>\n  );\n}',
    breakdown: [
      ['useState(0)', 'Start the count at zero.'],
      ['count', 'The value React remembers right now.'],
      ['setCount(count + 1)', 'Ask React to remember a new value.'],
    ],
    tryIt: 'Use the counter below. Then reset it and watch the number change.',
    remember: 'Use props for information given to a component. Use state for information the component changes.',
    demo: 'counter',
    source: react + 'state-a-components-memory',
  },
  {
    id: 'lists',
    group: 'React basics',
    title: 'Show a list',
    desc: 'Turn an array of data into repeated elements.',
    intro: [
      'React uses JavaScript’s map method to show one element for every array item.',
      'Each repeated element needs a stable key so React can keep track of it.',
    ],
    analogy: {
      title: 'Coat-check tickets',
      text: 'A key is like a coat-check ticket. Even if the coats move around, each ticket still identifies the right coat.',
    },
    syntax: 'const fruits = [\n  { id: 1, name: "Mango" },\n  { id: 2, name: "Banana" }\n];\n\nfunction FruitList() {\n  return (\n    <ul>\n      {fruits.map(fruit => (\n        <li key={fruit.id}>{fruit.name}</li>\n      ))}\n    </ul>\n  );\n}',
    breakdown: [
      ['fruits.map(...)', 'Run the same code for every fruit.'],
      ['<li>...</li>', 'Return one list item for each fruit.'],
      ['key={fruit.id}', 'Give React a stable ID for that item.'],
    ],
    tryIt: 'Add an orange object with its own id. Where will it appear?',
    remember: 'Use a real ID for the key when items can be added, removed, or moved.',
    source: react + 'rendering-lists',
  },
  {
    id: 'forms',
    group: 'React basics',
    title: 'Inputs and forms',
    desc: 'Keep what the visitor types in state.',
    intro: [
      'An input can read its value from state.',
      'Every edit updates that state, so the input and your code stay in sync.',
    ],
    analogy: {
      title: 'One shared notebook',
      text: 'The input and your code both read the same notebook. When the visitor types, the notebook changes. React then shows the new entry.',
    },
    syntax: 'function NameInput() {\n  const [name, setName] = useState("");\n\n  return (\n    <>\n      <input\n        value={name}\n        onChange={event => setName(event.target.value)}\n      />\n      <p>Hello, {name || "friend"}!</p>\n    </>\n  );\n}',
    breakdown: [
      ['value={name}', 'Show the current state inside the input.'],
      ['onChange', 'Run code whenever the visitor types.'],
      ['event.target.value', 'Read the latest text from the input.'],
    ],
    tryIt: 'Type in the example below. Notice that the greeting updates after every key press.',
    remember: 'An input with value also needs onChange, or the visitor cannot edit it.',
    demo: 'form',
    source: react + 'reacting-to-input-with-state',
  },
  {
    id: 'effects',
    group: 'React basics',
    title: 'Effects',
    desc: 'Connect a component to something outside React.',
    intro: [
      'Most components do not need an Effect.',
      'Use useEffect when you must connect to an outside system, such as a timer, browser API, or network connection.',
    ],
    analogy: {
      title: 'Plugging in a lamp',
      text: 'An Effect plugs your component into something outside it. The cleanup function unplugs the connection when it is no longer needed.',
    },
    syntax: 'import { useEffect } from "react";\n\nfunction Page() {\n  useEffect(() => {\n    document.title = "My page";\n\n    return () => {\n      document.title = "Website";\n    };\n  }, []);\n\n  return <h1>My page</h1>;\n}',
    breakdown: [
      ['useEffect(() => { ... })', 'Run this work after React updates the page.'],
      ['return () => { ... }', 'Clean up before the component goes away.'],
      ['[]', 'This Effect does not depend on changing props or state.'],
    ],
    tryIt: 'Name the outside system in this example. Hint: it belongs to the browser.',
    remember: 'Clicks belong in event handlers. Calculations belong in the component. Effects are for outside systems.',
    source: react + 'synchronizing-with-effects',
  },
];
